package dhl

// Generated by https://quicktype.io

type CreateShipmentRequest struct {
	ManifestRequest ManifestRequest `json:"manifestRequest"`
}

type ManifestRequest struct {
	HDR HDR `json:"hdr"`
	BD  BD  `json:"bd"`
}

type BD struct {
	PickupAccountID string         `json:"pickupAccountId"`
	SoldToAccountID string         `json:"soldToAccountId"`
	PickupAddress   PickupAddress  `json:"pickupAddress"`
	ShipperAddress  ShipperAddress `json:"shipperAddress"`
	ShipmentItems   []ShipmentItem `json:"shipmentItems"`
}

type PickupAddress struct {
	Name     string `json:"name"`
	Address1 string `json:"address1"`
	Country  string `json:"country"`
}

type ShipperAddress struct {
}

type ShipmentItem struct {
	ConsigneeAddress       map[string]string  `json:"consigneeAddress"`
	ReturnAddress          map[string]string  `json:"returnAddress"`
	ShipmentID             string             `json:"shipmentID"`
	DeliveryConfirmationNo string             `json:"deliveryConfirmationNo"`
	PackageDesc            string             `json:"packageDesc"`
	TotalWeight            int64              `json:"totalWeight"`
	TotalWeightUOM         string             `json:"totalWeightUOM"`
	DimensionUOM           string             `json:"dimensionUOM"`
	Height                 float64            `json:"height"`
	Length                 float64            `json:"length"`
	Width                  float64            `json:"width"`
	CustomerReference1     string             `json:"customerReference1"`
	CustomerReference2     string             `json:"customerReference2"`
	ProductCode            string             `json:"productCode"`
	Incoterm               string             `json:"incoterm"`
	ContentIndicator       string             `json:"contentIndicator"`
	CodValue               float64            `json:"codValue"`
	InsuranceValue         interface{}        `json:"insuranceValue"`
	FreightCharge          float64            `json:"freightCharge"`
	TotalValue             float64            `json:"totalValue"`
	Currency               string             `json:"currency"`
	Remarks                string             `json:"remarks"`
	ValueAddedServices     ValueAddedServices `json:"valueAddedServices"`
	BillingReference2      string             `json:"billingReference2"`
	BillingReference1      string             `json:"billingReference1"`
	IsMult                 string             `json:"isMult"`
	DeliveryOption         string             `json:"deliveryOption"`
	ShipmentPieces         []ShipmentPiece    `json:"shipmentPieces"`
	ShipmentContents       []ShipmentContent  `json:"shipmentContents"`
}

type ShipmentContent struct {
	SkuNumber         string  `json:"skuNumber"`
	Description       string  `json:"description"`
	DescriptionImport string  `json:"descriptionImport"`
	DescriptionExport string  `json:"descriptionExport"`
	ItemValue         float64 `json:"itemValue"`
	ItemQuantity      int64   `json:"itemQuantity"`
	GrossWeight       int64   `json:"grossWeight"`
	NetWeight         int64   `json:"netWeight"`
	WeightUOM         string  `json:"weightUOM"`
	ContentIndicator  string  `json:"contentIndicator"`
	CountryOfOrigin   string  `json:"countryOfOrigin"`
	HsCode            string  `json:"hsCode"`
}

type ShipmentPiece struct {
	PieceID           int64           `json:"pieceID"`
	AnnouncedWeight   AnnouncedWeight `json:"announcedWeight"`
	CodAmount         float64         `json:"codAmount"`
	InsuranceAmount   float64         `json:"insuranceAmount"`
	BillingReference1 string          `json:"billingReference1"`
	BillingReference2 string          `json:"billingReference2"`
	PieceDescription  string          `json:"pieceDescription"`
}

type AnnouncedWeight struct {
	Weight int64  `json:"weight"`
	Unit   string `json:"unit"`
}

type ValueAddedServices struct {
	ValueAddedService []ValueAddedService `json:"valueAddedService"`
}

type ValueAddedService struct {
	VasCode string `json:"vasCode"`
}

type HDR struct {
	MessageType     string `json:"messageType"`
	MessageDateTime string `json:"messageDateTime"`
	AccessToken     string `json:"accessToken"`
	MessageVersion  string `json:"messageVersion"`
}
